//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hastane_Otomasyonu__Güncel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoktorBilgileri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DoktorBilgileri()
        {
            this.HastaIslemleri = new HashSet<HastaIslemleri>();
            this.Recete = new HashSet<Recete>();
        }
    
        public int Id { get; set; }
        public string TCKN { get; set; }
        public string DoktorAdi { get; set; }
        public string DoktorSoyadi { get; set; }
        public string DoktorTelefon { get; set; }
        public Nullable<int> PoliklinikId { get; set; }
        public string DoktorSifre { get; set; }
    
        public virtual Poliklinikler Poliklinikler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HastaIslemleri> HastaIslemleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recete> Recete { get; set; }
    }
}
