//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hastane_Otomasyonu__Güncel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HastaIslemleri
    {
        public int Id { get; set; }
        public string HastaId { get; set; }
        public Nullable<int> PoliklinikId { get; set; }
        public Nullable<int> DosyaNo { get; set; }
        public Nullable<System.DateTime> SevkTarihi { get; set; }
        public Nullable<int> DoktorId { get; set; }
        public string OdemeSekli { get; set; }
        public Nullable<int> ToplamTutar { get; set; }
        public Nullable<System.DateTime> CıkısTarihi { get; set; }
    
        public virtual DoktorBilgileri DoktorBilgileri { get; set; }
        public virtual HastaBilgileri HastaBilgileri { get; set; }
        public virtual Poliklinikler Poliklinikler { get; set; }
    }
}
