//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hastane_Otomasyonu__Güncel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HastaneOtomasyonuGüncelEntities : DbContext
    {
        public HastaneOtomasyonuGüncelEntities()
            : base("name=HastaneOtomasyonuGüncelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DoktorBilgileri> DoktorBilgileri { get; set; }
        public virtual DbSet<HastaBilgileri> HastaBilgileri { get; set; }
        public virtual DbSet<HastaIslemleri> HastaIslemleri { get; set; }
        public virtual DbSet<Ilac> Ilac { get; set; }
        public virtual DbSet<PersonelGirisi> PersonelGirisi { get; set; }
        public virtual DbSet<Poliklinikler> Poliklinikler { get; set; }
        public virtual DbSet<Recete> Recete { get; set; }
        public virtual DbSet<ReceteIlac> ReceteIlac { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
