//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hastane_Otomasyonu__Güncel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonelGirisi
    {
        public int Id { get; set; }
        public string PersonelKullaniciAdi { get; set; }
        public string PersonelSifre { get; set; }
    }
}
