//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hastane_Otomasyonu__Güncel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recete
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recete()
        {
            this.ReceteIlac = new HashSet<ReceteIlac>();
        }
    
        public int Id { get; set; }
        public string HastaTCKN { get; set; }
        public Nullable<int> DoktorId { get; set; }
        public Nullable<System.DateTime> ReceteTarihi { get; set; }
    
        public virtual DoktorBilgileri DoktorBilgileri { get; set; }
        public virtual HastaBilgileri HastaBilgileri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceteIlac> ReceteIlac { get; set; }
    }
}
